spring:
    application:
        name: spring-ai-rag-towing-expert
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            embedding:
                options:
                    model: text-embedding-3-small
            chat:
                options:
                    model: gpt-4-turbo
asb:
    aiapp:
        vectoStorePath: /temp/vectorstore.json
        documentsToLoad: 
            - classpath:/movies500.csv
